name: Deploy to staging

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Configure gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.1
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}
      - run: npm ci
      - run: npm run build
      - run: gcloud app deploy --quiet --project web-dev-staging --no-promote --version $(node -e "console.log(require('crypto').createHash('md5').update(process.argv[1]).digest('hex'))" $GITHUB_REF)
      # TODO(samthor): Write generated hash to comment on PR.
